language: go
go: 1.12.x

services:
  - docker


before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t srgupta5328/go-k8s:0.0.4
  - docker push srgupta5328/go-k8s:0.0.4
  - docker build . -t srgupta5328/go-k8s:latest
  - docker push srgupta5328/go-k8s:latest

after-deploy:
  - "curl -X POST -H 'content-type: application/json' --url "$url" -d '{"application":"gWjmb9vjSkqmYK8v1j3NNA","parameters":{"commitId":"commitId_placeholder","repositoryNAME":"repositoryNAME_placeholder"}}'"