language: go
go: 1.12.x

services:
  - docker

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


before_install:
  - docker build . -t srgupta5328/go-k8s:0.0.3
  - docker push docker.io/srgupta5328/g-k8s:0.0.3
